# This is a template or framework for docker-compose application
# refer to url: 

version: '3'
services:
  onlyoffice-documentserver:
    container_name: "{{docker_appname}}"
    #build: {{docker_apps_dir}}/{{docker_appname}}
    image: onlyoffice/documentserver:latest
    volumes:
      - "{{docker_apps_dir}}/{{docker_appname}}/logs:/var/log/onlyoffice"
      - "{{docker_apps_dir}}/{{docker_appname}}/data:/var/www/onlyoffice/Data"
      - "{{docker_apps_dir}}/{{docker_appname}}/postgresql:/var/lib/postgresql"
    stdin_open: true
    tty: true
    # bridge, host, none...
    network_mode: bridge
    user: "{{docker_uid.stdout}}:{{docker_uid.stdout}}"
    expose:
      - '80'
      - '443'
    restart: always
    ports:
      - "{{docker_apps_onlyofficedocumentserver_port}}:80"
      
networks:
  default:
    external:
      name: "{{docker_addnetwork}}"
